### ISSUE TITLE
Include memory samples in TotalSamplesCount to react better to OOMKills

### ISSUE THREAD

**Issue by shreyas-s-rao** [gardener/autoscaler#101]
---
name: Bug Report
about: Report a bug
labels: kind/bug, area/auto-scaling

---

**What happened**:
VPA Recommender did not recommend proper memory targets after the pod was OOMKilled.

**What you expected to happen**:
VPA Recommender should have considered the memory usage during (or just before) the OOMKill and recommended a larger memory target so that the number of restarts during pod recovery would be minimized.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:
There is a [TotalSamplesCount](https://github.com/kubernetes/autoscaler/blob/3a69f118d95cd653bf101aecc0ea5e00bf7ba370/vertical-pod-autoscaler/pkg/recommender/model/aggregate_container_state.go#L100) variable which is calculated every time a usage sample is added to VPA recommender. The VPA recommender however updates it only for addition of CPU samples, but memory samples are not considered. During an OOM scenario, the cpu usage sample remains zero. This leads to TotalSamplesCount being 0. Hence even though VPA recommender records memory samples, it does not give any recommendation as the code flow checks for TotalSamplesCount > 0 to give a recommendation.

**Environment**:

**Comment by himanshu-kun** [comment]
@voelzmo is this issue still valid ?

**Comment by voelzmo** [comment]
I think given that we got a fix merged for https://github.com/kubernetes/autoscaler/issues/4981 so lets close this one.
/close
