### ISSUE TITLE
Expose `--ignore-taints` flag of CA on Gardener Shoot

### ISSUE THREAD

**Issue by AxiomSamarth** [gardener/autoscaler#106]
**What would you like to be added**:
An `--ingore-taints` flag has to be exposed on Gardener Shoot.

**Why is this needed**:
NVIDIA GPU drivers are installed before GPU-using pods get scheduled to a node. We would like to use the [same approach as OpenAI](https://openai.com/blog/scaling-kubernetes-to-7500-nodes/#activegputests), which is to have a taint on the node & this taint is removed once the drivers are installed. Autoscaler will not scale up a node in the GPU pool because the GPU-using pods do not tolerate this "GPU Not Ready" taint.

**Comment by AxiomSamarth** [comment]
Linked issue on gardener/gardener is [here](https://github.com/gardener/gardener/issues/5166)

**Comment by himanshu-kun** [comment]
shall we close this?

**Comment by AxiomSamarth** [comment]
Yes, closing this as the flag has now been exposed on the Shoot spec.
