### ISSUE TITLE
Maintain a release for each upstream cluster-autoscaler release

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/autoscaler#107]
# Stories
- As user I want the cluster-autoscaler to act properly, matching my Kubernetes version.
- As operator I want the same in order to deal with less end user questions/complaints.
- As provider I want the same in order to implement bin-packing that will be even more susceptible to such problems.

# Motivation
- With https://github.com/gardener/gardener/issues/5064, we see that the CA behaviour highly depends on the vendored K8s version.
- For compatibility reasons and to match the upstream compatibility statements.
- To have a fork that is updated on regular basis with a clear update/rebase strategy from the upstream.

# Acceptance Criteria
- [x] Our cluster-autoscaler fork to maintain a release for each upstream minor release (see https://github.com/kubernetes/autoscaler/tree/cluster-autoscaler-1.22.0/cluster-autoscaler#releases)
  <details>
  <summary>Example</summary>

  | K8s Version | Upstream CA | Gardener CA |
  | ----------- | ----------- | ----------- |
  | [1.23.0](https://github.com/kubernetes/kubernetes/releases/tag/v1.23.0)        | [1.23.0](https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.23.0)        | 1.23        |
  | [1.22.0](https://github.com/kubernetes/kubernetes/releases/tag/v1.22.0)        | [1.22.0](https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.22.0)        | 1.22        |
  | [1.21.0](https://github.com/kubernetes/kubernetes/releases/tag/v1.21.0)        | [1.21.0](https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.21.0)        | 1.21        |
  | ...         | ...         | ...         |

  </details>

**Comment by himanshu-kun** [comment]
@ialidzhikov We are ready with autoscaler v1.20 sync. 
But the versioning of g/autoscaler is `v0.` rather than `v1.`
I would like to hear your suggestion on how to go about with changing the versions so that we could release `v1.20.0` and not `v0.20.0`.
Would it be fine to just change the `VERSION` file to have `v1.20.0-dev` and let the gardener release process to take care of the release?

**Comment by ialidzhikov** [comment]
> Would it be fine to just change the VERSION file to have v1.20.0-dev and let the gardener release process to take care of the release?

Yes.

**Comment by himanshu-kun** [comment]
/close
As the autoscaler is synced till upstream 1.22
For later sync , I will create new issues per release.

**Comment by ialidzhikov** [comment]
There are still no releases for 1.23 and 1.24. When to expect them?

**Comment by himanshu-kun** [comment]
We plan to assign the sync of 1.23 to Rishabh , who'll be joining us from July 14th.
I have created issue to keep track for sync with 1.23 https://github.com/gardener/autoscaler/issues/135

**Comment by vlerenc** [comment]
Then let's reopen this one again, please (as it's not yet done, right?).

**Comment by ialidzhikov** [comment]
> /close as release 1.23 is done.

What about 1.24?

**Comment by himanshu-kun** [comment]
will create a seperate issue for that.
