### ISSUE TITLE
Integration test for Gardener Autoscaler

### ISSUE THREAD

**Issue by AxiomSamarth** [gardener/autoscaler#110]
**What would you like to be added**:
An integration test suite for Gardener Cluster Autoscaler that could be run both locally as well in the build pipeline with ease.

**Why is this needed**:
This is need to test the CA behaviour against an actual Shoot and to report any anomalies as such. Also, such an integration test suite would help in validating any adoptions/upgrades from upstream CA.

**Comment by AxiomSamarth** [comment]
Planned action items -

- [ ] Development of the integration test suite that runs locally. 
- [ ] Documentation
- [ ] Adopting the same onto the build pipeline.

**Comment by timebertt** [comment]
I think, you might be interested in envtest for this (in case you don't know it already), see https://book.kubebuilder.io/cronjob-tutorial/writing-tests.html and https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.11.0/pkg/envtest.

**Comment by AxiomSamarth** [comment]
Thanks @timebertt I will explore this more.
