### ISSUE TITLE
CA didn't scale up when current nodes was below min

### ISSUE THREAD

**Issue by prashanth26** [gardener/autoscaler#18]
# Issue
A cluster had only 4 nodes even though the CA min. nodes were set to 5. The CA didn't try to scale up the desired nodes.

cc: @mliepold

**Comment by vlerenc** [comment]
cc: @dguendisch

**Comment by hardikdr** [comment]
I think this is expected behavior from CA, hence closing the issue.
Ref: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#my-cluster-is-below-minimum--above-maximum-number-of-nodes-but-ca-did-not-fix-that-why
