### ISSUE TITLE
Issue for - Sync with Upstream v1.27.0

### ISSUE THREAD

**Issue by himanshu-kun** [gardener/autoscaler#191]
## What would you like to be added
Gardener autoscaler should be synced with respective [Kubernetes Autoscaler 1.x.y Release](https://github.com/kubernetes/autoscaler/releases/)

## Why is this needed

* To keep the fork in sync with upstream.
* To ensure the shoot control planes are using respective version of CA for a given K8S version

## Steps

- [ ] https://github.com/orgs/gardener/projects/22/views/10?pane=issue&itemId=22219948#:~:text=Support%20Debugging%20of%20Integration%20Tests%23185
- [ ] Please follow the steps in
[How do I sync gardener autoscaler with an upstream autoscaler minor release](https://github.com/gardener/autoscaler/blob/machine-controller-manager-provider/cluster-autoscaler/FAQ.md#how-do-i-sync-gardener-autoscaler-with-an-upstream-autoscaler-minor-release)

**Comment by rishabh-11** [comment]
With Kubernetes 1.27, the feature gates `CSIMigration` and `CSIMigrationAWS` will not be supported anymore. See [this](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/#descriptions-for-removed-feature-gates).
CSIMigration PR on gardener, which mutates CA feature gates by gardener extensions -> https://github.com/gardener/gardener/pull/6047/. Just keep in mind to take care of this.
