### ISSUE TITLE
Clean up the repo to make rebasing with upstream as automatic as possible

### ISSUE THREAD

**Issue by amshuman-kr** [gardener/autoscaler#24]
### Issue

The current changes in this fork make it hard to automatically rebase to upstream changes. Due to this, further manual changes are required every time we want to take in changes from upstream.

This following list is the chronological order of our commits as far as I can see. It needs to be verified to see if I have missed anything.
1. https://github.com/gardener/autoscaler/commit/c828a5be1afcd707421ec3e11dcd41200a848a90 
Deleting addon-resizer and vertical-pod-autoscaler makes it hard to rebase in the future. And we would need to keep rebasing in the near future until the machine-api is integrated with cluster-autoscaler. It would be better to retain them until then. So, may be better to remove this commit during the cleanup.
2. https://github.com/gardener/autoscaler/commit/f07b4d50c3767b985b7a484620b52f29a83b59a6
3. https://github.com/gardener/autoscaler/commit/915aca84f5e14e1d9e5390ddc2b28ff0db572d20
4. https://github.com/gardener/autoscaler/commit/40285d16008ab3803fdedd201d27e2f2754a5e80
5. https://github.com/gardener/autoscaler/commit/da5e1bc8188a333a949d51310fa7daf4fe24c913
6. https://github.com/gardener/autoscaler/commit/d3886a5a60e6855b558ff7614703482c341bd14c
7. https://github.com/gardener/autoscaler/commit/13d61043df474a6b8f9eb47144c18e50f813b9f0
8. https://github.com/gardener/autoscaler/commit/5167fdde8e278eaea19ac7a32318e8accc068a2c
9. https://github.com/gardener/autoscaler/commit/1ce7d24eff25cc66a53db70b9e7a191836ddccb0
10. https://github.com/gardener/autoscaler/commit/6f9a4ac90b79ffcb66097bb85246487d8a1af093
11. https://github.com/gardener/autoscaler/commit/b8fb38745265e91ade9376a90d97b2860cbe6823
12. https://github.com/gardener/autoscaler/commit/da7c71678535048676326657533e94c50da23dbc
13. https://github.com/gardener/autoscaler/commit/1ea00cd6b6b9699babe98f3bd936d5c2455a3f0b
14. https://github.com/gardener/autoscaler/commit/7bd5249cd9b485a3c11f9081c38e17ae9cb3e236
15. https://github.com/gardener/autoscaler/commit/a128cc96de5366706083997a0a0e4c6f4b4d2366 
Retaining the package name/path would ease future rebases. Might be better to remove this commit during the cleanup.
16. https://github.com/gardener/autoscaler/commit/333fcb9bcfd5dbed18a5b86da751790a9ba66e1b
17. https://github.com/gardener/autoscaler/commit/ddf86929460aedc9297435d82b5521d9e19ddc3a
18. https://github.com/gardener/autoscaler/commit/55e365efd9e5cade4d72a2e6f8aa8c27ecdf6ab7
19. https://github.com/gardener/autoscaler/commit/0db747e2cbb352ccff4ebca671af28ba89f5ce24
20. https://github.com/gardener/autoscaler/commit/3168a9f9338b6ddc40db8f4f4035000b19b24c6a
21. https://github.com/gardener/autoscaler/commit/aeee88e94e400727a77bcc769a96c3e64812bfd2
22. https://github.com/gardener/autoscaler/commit/1b9574f8685308be4675d215b10321618f73e7ea
23. https://github.com/gardener/autoscaler/commit/dde3cfb5192a645c448c957f8867e77713e94534
24. https://github.com/gardener/autoscaler/commit/3f3a734a5ef72b117648f0f2670b30c8eba37ea0
25. https://github.com/gardener/autoscaler/commit/7f4f7ba2b2cfae8736d7d827a4a072a0f9fa647a
26. https://github.com/gardener/autoscaler/commit/41c804969eace6b6c5a3b26691125c88587baaea
27. https://github.com/gardener/autoscaler/commit/03b20e55ec709595419d5046944ab9524edff8dc
Retaining the package name/path would ease future rebases. Might be better to remove this commit during the cleanup.
28. https://github.com/gardener/autoscaler/commit/f454c48fa536e42ecaf494043b95c59a59793270
29. https://github.com/gardener/autoscaler/commit/1bfd5b7e9fafe7db1b303e98e02caf618ded3a3a
30. https://github.com/gardener/autoscaler/commit/beb681d5e9e46229481c26709efc5fba128c7b9a
31. https://github.com/gardener/autoscaler/commit/01144f3ab8d273f0eb3ad652cd86e095ad0afee8
32. https://github.com/gardener/autoscaler/commit/bb50fb3af1d369618087b0867686bbf1aa58e2ca
33. https://github.com/gardener/autoscaler/commit/f0ceff81b267ec2c48ee73ad0f2ff03b9749d375
34. https://github.com/gardener/autoscaler/commit/af07a756598f1d96e31239f0e4ba6bf455e540b2
35. https://github.com/gardener/autoscaler/commit/f0810742f73547ccd2ef261be54bdde33b6db497
36. https://github.com/gardener/autoscaler/commit/e33a0c4599f0d2615520e6250bb5dff8e16c16dd
37. https://github.com/gardener/autoscaler/commit/fc07919d001127ea00f759079899fa39e7e9669d
38. https://github.com/gardener/autoscaler/commit/55d7cc1c6dd74b594237de3b7c0ea980c77dd844

### Solution
We need to refactor the repo to avoid some changes (like package renaming, deletion of folders etc.) and mark other unavoidable changes explicitly so that we can automate much of the work while rebasing on upstream.

Also, it is will be a good idea to make commits that deviate from upstream easily identified. Preferably, it is better to keep them always together and on top of the upstream commit so that future rebasing goes as smoothly as possible. I.e. We should avoid cherry picking.

**Comment by prashanth26** [comment]
close in favour of https://github.com/gardener/autoscaler/issues/51

**Comment by hardikdr** [comment]
I think, this issue is about the larger rebase, considering all the patches. While the one you linked above is only about one very specific update from upstream.
I'd prefer to keep this open.

**Comment by hardikdr** [comment]
Here's the new branch - https://github.com/gardener/autoscaler/tree/machine-controller-manager-provider
- for a cleaner history.
- Easier rebase in the future.
This is also now a default branch for the fork.

**Comment by hardikdr** [comment]
cc @rewiko
