### ISSUE TITLE
Scale from Zero doesn't work in case of pods with PVs

### ISSUE THREAD

**Issue by himanshu-kun** [gardener/autoscaler#245]
**What happened**:

Customer had a pod with PV and a node group which scales from zero. When the customer hibernates the cluster (means nodegrp scaled down to zero) and then wake-it up again (means pod gets deployed , and old PVC, PV already present) then the scale-up from zero doesn't happen.

This behaviour is not observed when pod uses a new PVC (which doesn't have an associated PV)

**What you expected to happen**:
Scale from zero to work everytime

**How to reproduce it (as minimally and precisely as possible)**:
explained above

**Anything else we need to know**:
This is happening because there are `topology.ebs.csi..` labels which are placed by KCM on the node and the affinity is placed on the PV by the csi-driver for zone pinning.
But the autoscaler is not aware of these labels, and the labels vary from provider to provider.
This is why scale from 1 scenario passes while scale from zero fails

The issue has been fixed for [AWS](https://github.com/gardener/autoscaler/issues/83) , [Azure](https://github.com/gardener/autoscaler/issues/113) and [GCP](https://github.com/gardener/autoscaler/issues/182) , but is left for other providers listed below
- [x] Openstack
  - [x] cinder csi driver
  - [x] manilla csi driver (topology.manila.csi.openstack.org/zone should be added) refer live ticket 3737
- [x]  Alicloud
- [x]  Vsphere
- [x] AWS
- [x] Azure
- [x] GCP

**Environment**:

CA 1.27.0 and less

**Comment by himanshu-kun** [comment]
/priority 2
/assign @himanshu-kun 

important to be implemented before https://github.com/gardener/gardener/issues/7857

**Comment by briantopping** [comment]
Hi I think we have answered relevant questions for vSphere. The documentation misrepresents that the vSphere backend should be a specific version. As maintainer of that plugin, this doesn't need to be a concern. 🤓

**Comment by ashwani2k** [comment]
Can we update the issue with the corresponding provider specific PRs to make it easy to track them later when required.

**Comment by elankath** [comment]
Updating issue with relevant PR's
- [x] openstack cinder: https://github.com/gardener/gardener-extension-provider-openstack/pull/659
- [x] openstack manila: https://github.com/gardener/gardener-extension-provider-openstack/pull/674
- [x] azure: https://github.com/gardener/gardener-extension-provider-azure/pull/436
- [x] aws: https://github.com/gardener/gardener-extension-provider-aws/pull/365
- [x] gcp: https://github.com/gardener/gardener-extension-provider-gcp/pull/591
- [x] vsphere: https://github.com/gardener/gardener-extension-provider-vsphere/pull/463
- [x] alicloud: https://github.com/gardener/gardener-extension-provider-alicloud/pull/638
