### ISSUE TITLE
Cluster autoscaler is triggered during provisioning of PVC

### ISSUE THREAD

**Issue by dtsvetkovsap** [gardener/autoscaler#28]
During scheduling of a StatefulSet, PVCs are being provisioned for the pods. During that time, the pods are triggering an event FailedScheduling because the PVC is still not ready. Although this does not last long, it triggers an event TriggeredScaleUp.

This seems to have been resolved in an issue in Kubernetes Github project - https://github.com/kubernetes/autoscaler/issues/923

Can the same be applied to Gardener autoscaling because the second node is not really needed as there seem to be available resources on the first node.

**Comment by prashanth26** [comment]
Hi @dtsvetkovsap ,

We use a forker version of the upstream autoscaler and seems have been fixed upstream. We have the task of rebasing our autoscaler with the upstream one. And once that's done this issue should be fixed.
