### ISSUE TITLE
Fix edge case mentioned in https://github.com/gardener/autoscaler/pull/215

### ISSUE THREAD

**Issue by rishabh-11** [gardener/autoscaler#328]
**What happened**:
In live issue 5658, we see that the edge case mentioned in the PR #215 is hit and an incorrect machine object is deleted.

**What you expected to happen**:
The correct machine object should be deleted.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:
Solution:-
1. If scaling down of MCD fails, reset the priority of the corresponding machines
2. In Refresh Method, do the following:-
    1. Get the mcd replicas, r1.
    2. availMachines = Total Machine Objects - Machines having Prio 1 Annotation
    3. If r1 == availMachines, return
    4. If r1 > availMachines, then order machines with prio 1 annotation based on Creation Timestamp(desc order).
    5. From the above ordered list, pick up r1-availMachines and reset their priority.

**Environment**:

**Comment by CGilde** [comment]
Hi @rishabh-11, any plan when a fix will be available?
Thanks, Chris

**Comment by rishabh-11** [comment]
Hi @CGilde, TBH it will take some time but this issue is on our list. We'll take care of it in this quarter.
