### ISSUE TITLE
Autoscaler should pick alternate worker-pool if chosen one can't be scaled-up.

### ISSUE THREAD

**Issue by hardikdr** [gardener/autoscaler#35]
## Description: 

Since recently, we have been seeing resource-scarcity on multiple cloud-providers, where requested machine-types are not available in many regions. With a fresh workload, cluster-autoscaler keeps scaling up the same worker-pool with unavailable machine-type/region, while other worker-pools with different machine-type/region could host the load. This leads to unnecessarily large and unpredictable waiting every time a new workload is introduced. 

Autoscaler currently seems to be supporting following main features which could be useful in mitigating this:
1.  Back-off : 
    - If a new machine doesn't join the cluster after `MaxNodeProvisionTimeout`[~15mins], it declares the worker-pool to be unhealthy, and backs off its scale-up. 
    - Upon failed scale-up, it initially backs-off the worker pool for 5mins, gradually increasing it till 30mins.  This means, given worker pool will not be considered for scale-up for 30 mins. Backoff resets to 5mins after 3hours of timeout. 
     - A faulty worker-pool is declared healthy again if the desired count for the number of `running`machines and registered  `nodes` matches after an on-going back-off period[<30mins].
     - Refer [code](https://github.com/gardener/autoscaler/blob/machine-controller-manager/cluster-autoscaler/clusterstate/clusterstate.go#L46-L55) for actual parameters.

2. Fixes the node-group.
   - If the scale-up fails for the given worker-pool twice, it reduces the count for the desired number of machines in machinedeployment to the currently registered number of healthy `nodes-objects`. 
    - This code-path complements the back-off behavior above, as when node-group is fixed, the backed-off node-group is declared healthy again, as desired and the actual number of machines match.

Ideally, a combination of [1] and [2] would have sufficed if a node-group is not declared healthy again to scale-up, after it is fixed.
   - As node-group is declared healthy, every time a fresh workload is seen, the same node-group with unavailable machine-types/region could be chosen, leading to a long wait time of 2*`MaxNodeProvisionTimeout`. 
   - This could get even worse if the newly chosen alternate node-group after the 2*`MaxNodeProvisionTimeout` also does not have requested machine-types. 
   - With more node-groups, this can lead to unpredictably longer wait time for the fresh workload, which is undesirable.

As a side note, just to mention, none of the cloud providers [afaik] provides APIs to know beforehand if instances with the given machine-type are available in certain regions. 

## Possible solution:
- Enhance machine-controller-manager:
    - We could adapt MCM to set the annotation `out-of-resources: true` on the MachineDeployment whenever certain log-message is seen from the cloud-provider. 
    - Then adapt the mcm-provider of the autoscaler to ignore the node-group for scale-up taking the hint from the above annotation. 
- The feasibility of this approach has to be verified yet from the autoscaler-side.

Open for further discussions around possible solutions.

**Comment by hardikdr** [comment]
cc @vlerenc @ggaurav10 @prashanth26

**Comment by hardikdr** [comment]
The same proposed solution can also be used to disable the scale-down of the node-groups, specifically the ones whose machine-types are not available. 
- This is to not lose at least the existing capacity, with the consent from the user via configuration.

**Comment by vlerenc** [comment]
If the annotation is set at the `machinedeployment`, it will be also available at the `node` resources, right? In that case, users would know. When they touch the spec again or once every 24h when the cluster reconciles (or that process is triggered manually), it would be quasi reset, so users could also remove the annotation, should they increase their quota or learn that the problem or shortage was resolved. Not ideal, but it sounds acceptable for this kind of extreme situation, I would think.

**Comment by hardikdr** [comment]
I took a little further look into it.
Following solution overall sounds reliable:
1. Changes at MCM:
   - Update the machine-controller to add the annotation of `cloudprovider/out-of-resources: True`, whenever a specific log-pattern/error-code is seen. 
        - Please feel free to suggest a more suitable key/value for the annotation. 
        - Just to mention, as an alternative, we could simply rely on the `MachineDeployment.Status`  but we'd have lesser control over how the status is transitioned based on reconciliation.

2. Changes at Autoscaler:
   - Adapt the scale-up behavior [here](https://github.com/gardener/autoscaler/blob/machine-controller-manager/cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go#L245), to simply deny if a certain annotation is set on the machine-deployment. 

As mentioned, the shoot-reconciliation should reset the annotation every 24h, which would be the quasi-reset for the mechanism.
- End users can check the node-annotations to verify if the node-group is frozen due to resource-capacity issue. 
- End-users can either trigger the-conciliation of the shoot, which will reset the annotation. 

Important to note:
- Though MCM set the annotation immediately it sees the resource-out-of-capacity error, for autoscaler, it will take one scale-up to fail to realize this worker pool is unhealthy. 
- Declaring the failure of scale-up takes 15mins[timeout]. This can be reduced by end-user setting the flag [MaxNodeProvisionTime](https://github.com/gardener/autoscaler/blob/machine-controller-manager/cluster-autoscaler/main.go#L123) on the cluster-autoscaler-config in shoot-resource. [need to verify if shoot-gives this configurability already]

Any feedback?

**Comment by vlerenc** [comment]
Thank you for the proposal @hardikdr. How much complexity did that introduce? All these changes scare me a bit as they touch multiple components and put a band-aid on a very specific problem that was reported now in 3y of this project for the first time (in an exceptional situation/the COVID-19 crisis). I am also worried that this feature may break later, because it will be infrequently applied. Like commented out code, it may age quickly. WDYT? How safe is it? How can it be tested?

**Comment by hardikdr** [comment]
Yes, the solution did introduce dependent changes at multiple components[mcm, autoscaler], and hence a bit of complexity. I tested it by manually injecting the log-messages in the controller, we had seen earlier from Azure when resources are out of capacity. 

Overall, an alternate solution could be to bring everything into autoscaler, and not touch MCM, autoscaler reads the FailedMachineSummary, finds the log-patters and avoids scaling-up. That needs further experiments.
I also asked the stakeholders, if they are really seeing the issue happening yet at Azure, or is it getting better as it's already May. And if it's not really needed we could simply hold this work for now.

**Comment by jsravn** [comment]
I opened a PR so the autoscaler will make progress even if instances fail to start (e.g. due to InsufficientInstanceCapacity). It's not perfect however - as it relies on the autoscaler to timeout the node pool (15m by default, this can be reduced though - 5m seemed to work well for me in testing). Ideally we could mark node pools as unhealthy immediately which I believe will require MCM changes.

**Comment by hardikdr** [comment]
/close in favor of https://github.com/gardener/autoscaler/pull/58 .
For now, we live with 15m delay before picking up the alternate worker-pool, not impacting MCM to also be adapted.
Let's re-open if we see a need in future.
