### ISSUE TITLE
Autoscaler can't scale-up the node-group with all unschedulable nodes.

### ISSUE THREAD

**Issue by hardikdr** [gardener/autoscaler#36]
**What would you like to be added**:  
We observed autoscaler can't scale-up the node-group if all the nodes in the group are cordoned.
This could likely to be happening due to this [code-path](https://github.com/gardener/autoscaler/blob/machine-controller-manager/cluster-autoscaler/core/utils.go#L253).

We should either remove this check from upstream CA or from our fork. 
**Why is this needed**:

**Comment by vlerenc** [comment]
Thanks for opening @hardikdr. The other thing I didn't understand in that case is why 2 out of the 3 zoned worker pools where unschedulable. Who did that? The user, was it related to the pod with pdb=0 that couldn't be taken off, something else?

**Comment by hardikdr** [comment]
>why 2 out of the 3 zoned worker pools where unschedulable.

I also could not understand this part. I checked the machines were not tainted via the machine-deployment's `NodeSpec` either. The user's take on this would be very useful to understand it further.

Machines are generally tainted unschedulable by CA/MCM, only when they are marked for deletion. This was not the case either when I checked.


>The user, was it related to the pod with pdb=0 that couldn't be taken off, something else?

I can't think of a case, where pdb issue could bring the cluster in such tainted worker-pools. It seems very less likely to be the culprit.

**Comment by vlerenc** [comment]
OK, thank you @hardikdr. Even if the user did it manually and this is nothing, we still learned something interesting from this discussion ([code-path](https://github.com/gardener/autoscaler/blob/machine-controller-manager/cluster-autoscaler/core/utils.go#L253)), so that's good. 👍

**Comment by vlerenc** [comment]
You mentioned out-of-band more information. Shall we keep the issue or close it with "works as expected" and not intervene?

**Comment by hardikdr** [comment]
I think this issue can be closed, nothing much we can do. This is expected behavior from Autoscaler.
Related discussion for reference: https://github.com/kubernetes/autoscaler/commit/ea7bd81681f874c03a1aed0611768f3e538f158c
