### ISSUE TITLE
Consider the update from upstream

### ISSUE THREAD

**Issue by hardikdr** [gardener/autoscaler#51]
**What would you like to be added**: We might want to rebase to the latest version sooner as possible considering the following update from upstream: https://github.com/kubernetes/autoscaler/issues/3224 .
- It can affect the scale-up for init containers based pods.

**Comment by amshuman-kr** [comment]
Can we do this rebase in such a way as to make future rebasing smoother by keeping deviations from upstream to an easily identifiable minimum, grouped together on top of the upstream changes?

See #24 for more.

**Comment by hardikdr** [comment]
Agreed, we seem to have messed it in the past by modifying the imports, in the core of it. We should keep the core-logic clean/untouched for easy rebase. I'll make the changes this time in the upcoming rebase.

Btw @prashanth26, do you remember any good reason behind changing the imports back then? Or are there any blockers otherwise?

**Comment by prashanth26** [comment]
No @hardikdr . I am unable to recollect the exact reason. But i think it had something to do with vendoring issues. I think we can revert that change to imports and core and see if it works to keep the previous imports.

**Comment by prashanth26** [comment]
Consider this while making this update - https://github.com/gardener/autoscaler/issues/32#issue-575178547

**Comment by hardikdr** [comment]
This should be fixed with the recent autoscaler rebase.
/close
