### ISSUE TITLE
main loop is very slow due to NodeGroupForNode performing a full machine list

### ISSUE THREAD

**Issue by jsravn** [gardener/autoscaler#72]
**What happened**:
I've been investigating why cluster-autoscaler is very slow in our cluster, with hundreds of managed nodes taking 5m+ to perform a single reconcile loop.

After digging for a while with `-v8`, it seems that we're getting throttled due to the large number of requests for `machines` against the apiserver. It looks like the main culprit here is the `NodeGroupForNode`/`ReferenceFromProviderID` implementation, which does a basic full list of the machines for each node as the cluster-autoscaler goes through them. This then gets throttled by client-go down to 200ms per request.

**What you expected to happen**:
The mcm cloud provider shouldn't be doing straight GETs of kubernetes resources. It should be using shared informers or another caching mechanism to efficiently query the state of the apiserver.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:
If I have time, I will try to put together a PR to improve this.

**Environment**:

**Comment by prashanth26** [comment]
Hi @jsravn ,

Thanks for this investigation and for opening up this issue. We were aware of this enhancement/optimization however had been postponing it in the interest of time/bandwidth. However, we weren't aware that this issue affects workloads this way.

**Comment by prashanth26** [comment]
I just quickly looked through the code and couldn't stop thinking about the issue you had raised. And it looks like there were minor changes to incorporate cached clients but were never really used properly. Not sure why the case was. Anyways definitely looks like it needs fixing. 

I have created a quick PR to fix the same, refer - https://github.com/gardener/autoscaler/pull/73. I haven't tested it yet. Will test it and update the PR.

**Comment by prashanth26** [comment]
Hi James Ravn,
I am nearly done with this PR - https://github.com/gardener/autoscaler/pull/73. PTAL if you have some time.

**Comment by prashanth26** [comment]
@jsravn - This issue has been fixed with - https://github.com/gardener/autoscaler/releases/tag/v0.15.0.
