### ISSUE TITLE
Expose CA metrics on Gardener dashboards

### ISSUE THREAD

**Issue by prashanth26** [gardener/autoscaler#74]
**What would you like to be added**:
Expose CA metrics on Gardener Grafana dashboard. 

**Why is this needed**:
The CA metrics aren't being exposed correctly on the dashboard, probably an configuration issue. We would like to fix this so that customers and operators can review these metrics to improve/act on their workloads.

**Comment by himanshu-kun** [comment]
## Post grooming decision

Upstream autoscaler metrices -> https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/proposals/metrics.md

FAQ -> https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-monitor-cluster-autoscaler

**Comment by aaronfern** [comment]
Closing this issue in favour of the following 2 issues that tackle this same problem
1. https://github.com/gardener/autoscaler/issues/254 -> allow prometheus in g/g to scrape CA metrics
2. https://github.com/gardener/autoscaler/issues/264 -> To create dashboards to highlight important data

/close
