### ISSUE TITLE
AWS u-6tb1.112xlarge machine isn't scaled up

### ISSUE THREAD

**Issue by antcs** [gardener/autoscaler#84]
**What happened**:
Tried to provision a HANA instance onto a u-6tb1.112xlarge machine.

The autoscaler log is showing following behavious:

```
E0610 13:15:22.116394       1 static_autoscaler.go:271] Failed to get node infos for groups: Unable to fetch details for VM type u-6tb1.112xlarge
E0610 13:15:32.123466       1 utils.go:119] Unable to build proper template node for shoot--hc-dev--demo-hc-3-haas-hana-xxl-z1: Unable to fetch details for VM type u-6tb1.112xlarge
```

In addition the type is not in the list of known instances:
https://github.com/gardener/autoscaler/blob/machine-controller-manager-provider/cluster-autoscaler/cloudprovider/aws/ec2_instance_types.go#L2239-L2250

**What you expected to happen**:
That the autoscaler spins up a u-6tb1.112xlarge machine

**How to reproduce it (as minimally and precisely as possible)**:
Create a pod that should be scheduled onto a u-6tb1.112xlarge machine and set the minimum of that worker group to 0

**Anything else we need to know**:
Issue was already discussed in the #sap-tech-gardener-canary: https://ddm-hana.slack.com/archives/CBV3JS9S4/p1623262858312900

**Environment**:
Gardener Canary

**Comment by prashanth26** [comment]
Changes required are merged. However, it is yet to propagated to the landscape.
