### ISSUE TITLE
Cluster autoscaler scale replicas to below the Min. value

### ISSUE THREAD

**Issue by prashanth26** [gardener/autoscaler#87]
**What happened**:
The machineDeployment `shoot--project--shoot--deployment` desired replicas, for one of the replicas whose desired value should have been `1` as the Min was set to `1`. However, for some reason, the desired replicas were changed to `0` by cluster autoscaler (I think).

I see the following on cluster-autoscaler.

```
2021-06-10 15:19:51 | {"log":"Some node group target size was fixed, skipping the iteration","pid":"1","severity":"INFO","source":"static_autoscaler.go:351"}
-- | --
  |   | 2021-06-10 15:19:51 | {"log":"Decreasing size of shoot--project--shoot--deployment, expected=1 current=0 delta=-1","pid":"1","severity":"INFO","source":"static_autoscaler.go:572"}


2021-06-10 15:17:51 | {"log":"Some node group target size was fixed, skipping the iteration","pid":"1","severity":"INFO","source":"static_autoscaler.go:351"}
-- | --
  |   | 2021-06-10 15:17:51 | {"log":"Decreasing size of shoot--project--shoot--deployment, expected=1 current=0 delta=-1","pid":"1","severity":"INFO","source":"static_autoscaler.go:572"}

```

I suspect that the cluster autoscaler is getting a stale value of replicas from the cached machine deployment leading to this state. Probably a side effect of this change - https://github.com/gardener/autoscaler/pull/73. We might have to relook at the cluster autoscaler code. 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Is a rare occurance. However the second part of the issue is reproducable. 

1. Create a machineDeployment with Min:1 and Max:>=1
2. Manually scale down the replicas to 0
3. Ideally CA should have reverted the replicas to 1, however it doesn't.

**Anything else we need to know**:

**Environment**:
/platform azure
/platform OpenStack
Kubernetes version: `v1.20.6`

**Comment by himanshu-kun** [comment]
/close 
/duplicate #30 
no stale data issue, its a behavior of autoscaler
